### ISSUE TITLE
Discrepancy between YAML test results and foma FST output

### ISSUE THREAD

**Issue by coxchristopher** [giellalt/lang-srs#3]
Running `make check` in the current repository produces expected (i.e., passing) results for all but one of the YAML tests found in [test/src/gt-norm-yamls/](https://github.com/giellalt/lang-srs/tree/main/test/src/gt-norm-yamls).  With [V-INTR-IPFV_REP-0i-tsidiitla_run-away_gt-norm.yaml](https://github.com/giellalt/lang-srs/blob/main/test/src/gt-norm-yamls/V-INTR-IPFV_REP-0i-tsidiitla_run-away_gt-norm.yaml), however, `make check` fails gloriously, with none of the forms in the test being recognized or generated:

`YAML test 8: analyser-gt-norm.hfstol + gt-norm-yamls/V-INTR-IPFV_REP-0i-tsidiitla_run-away_gt-norm.yaml - 0/24/24 FAIL`

Inspecting these results more closely suggests that the normative isn't producing or accepting any forms/analyses for this lexical entry:

```
--------------------------------------------------------
Test 0: Verb - tsídiitł'á[run-away] (Lexical/Generation)
--------------------------------------------------------
[ 1/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg1 => Missing results: nátsídistł'ásh
[ 1/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg1 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg1+?
[ 2/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg2 => Missing results: nátsídíítł'ásh
[ 2/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg2 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg2+?
[ 3/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg3 => Missing results: nátsídiitł'ásh
[ 3/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg3 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg3+?
[ 4/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl1 => Missing results: nátsídiìtł'ásh, nátsídaàtł'ásh
[ 4/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl1 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+?
[ 5/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+Distr => Missing results: nádàtsídiìtł'ásh, nádàtsídaàtł'ásh
[ 5/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+Distr => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+Distr+?
[ 6/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl2 => Missing results: nátsídastł'ásh
[ 6/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl2 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl2+?
[ 7/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl2+Distr => Missing results: nádàtsídastł'ásh
[ 7/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl2+Distr => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl2+Distr+?
[ 8/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl3 => Missing results: nátsígídiitł'ásh
[ 8/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl3 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl3+?
[ 9/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl3+Distr => Missing results: nádàtsígídiitł'ásh
[ 9/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjPl3+Distr => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl3+Distr+?
[10/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg4 => Missing results: nátsíts'ídiitł'ásh
[10/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg4 => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg4+?
[11/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg4+Distr => Missing results: nádàtsíts'ídiitł'ásh
[11/11][FAIL] tsídiitł'á+V+I+Ipfv+Rep+SbjSg4+Distr => Unexpected results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg4+Distr+?

Test 0 - Passes: 0, Fails: 11, Total: 11
------------------------------------------------------
Test 1: Verb - tsídiitł'á[run-away] (Surface/Analysis)
------------------------------------------------------
[ 1/13][FAIL] nátsídistł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg1
[ 2/13][FAIL] nátsídíítł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg2
[ 3/13][FAIL] nátsídiitł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg3
[ 4/13][FAIL] nátsídiìtł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1
[ 5/13][FAIL] nátsídaàtł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1
[ 6/13][FAIL] nádàtsídiìtł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+Distr
[ 7/13][FAIL] nádàtsídaàtł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl1+Distr
[ 8/13][FAIL] nátsídastł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl2
[ 9/13][FAIL] nádàtsídastł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl2+Distr
[10/13][FAIL] nátsígídiitł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl3
[11/13][FAIL] nádàtsígídiitł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjPl3+Distr
[12/13][FAIL] nátsíts'ídiitł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg4
[13/13][FAIL] nádàtsíts'ídiitł'ásh => Missing results: tsídiitł'á+V+I+Ipfv+Rep+SbjSg4+Distr

Test 1 - Passes: 0, Fails: 13, Total: 13
Total passes: 0, Total fails: 24, Total: 24
```

What's unusual about this is that the current FST _does_ produce and accept these forms before it's stitched into the larger Giella infrastructure. Compiling the FST and loading the resulting code into foma with

```
$ make
$ cd src/fst
$ foma -l verb_lexicon.xfscript
```

produces all of the forms listed in the corresponding YAML test:

```
foma[1] pairs
(...)
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg1	nátsídistł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl1	nátsídiìtł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl1	nátsídaàtł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl1+Distr	nádàtsídiìtł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl1+Distr	nádàtsídaàtł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg2	nátsídíítł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl2	nátsídastł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl2+Distr	nádàtsídastł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg3	nátsídiitł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl3	nátsígídiitł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjPl3+Distr	nádàtsígídiitł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg4	nátsíts'ídiitł'ásh
tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg4+Distr	nádàtsíts'ídiitł'ásh
```

(The foma output includes the gloss string "[run-away]", but this is also present in the [lexical entries associated with the four other YAML test files related to this lemma](https://github.com/giellalt/lang-srs/blob/334c8e5b1568bd446b4cd4e1b6f1ff1d3f9ce944/src/fst/stems/verb_stems.lexc#L42), all of which are passing with flying colours, so having this string stripped out during the compilation process shouldn't be the source of the problem.)

I've been poking around with this test at various points over the past week, and I haven't been able to figure out why the FST would be producing and accepting the expected forms with foma, but not with the normative FST used with HFST for the YAML tests.  I'm wondering if this might not be related to the issue that @aarppe reported earlier in this repository. @snomos, would you happen to know if this is something that other Giella projects might have run into in the past?

**Comment by snomos** [comment]
> (The foma output includes the gloss string "[run-away]", but this is also present in the [lexical entries associated with the four other YAML test files related to this lemma](https://github.com/giellalt/lang-srs/blob/334c8e5b1568bd446b4cd4e1b6f1ff1d3f9ce944/src/fst/stems/verb_stems.lexc#L42), all of which are passing with flying colours, so having this string stripped out during the compilation process shouldn't be the source of the problem.)

Turns out it is, for reasons beyond me. Here's the evidence:

```sh
echo "tsígídìstł'ò" | hfst-lookup -q src/analyser-gt-norm.hfstol 
tsígídìstł'ò	tsídiitł'á+V+I+Pfv+SbjPl3	0,000000

echo "nátsídistł'ásh" | hfst-lookup -q src/analyser-gt-norm.hfstol 
nátsídistł'ásh	tsídiitł'á[run-away]+V+I+Ipfv+Rep+SbjSg1	0,000000
```

That is, for the REP forms, the gloss is retained, for the other forms it is not. I really do not understand why this happens. The solution is to generalise the gloss removing regex as it was earlier, with the slight risk that it may remove more than we want.

With this change all yaml tests are passing for me.

**Comment by aarppe** [comment]
Another matter which may be related here is that the final contlexes set the flag for the superaspect with a P-flag; however there is no matching R or U flag later on, so such a P-flag will have no effect. Also, an earlier R-flag in any of the inflectional lexc files would fail, since this P-flag is set after invoking such an R-flag.

The solution is to 1) use an U or R flag in the stems file, and then 2) ensure that a matching U or P flag is set up in the inflectional lexc files. Point 1 is achieved by the current lexc generation script, but point 2 would need a manual check/correction.

**Comment by coxchristopher** [comment]
Ah, that's great -- thanks for taking the time to look into this, @snomos!  All of the YAML tests now pass for me, too.

@aarppe: I think the matching `@R.SUPERASPECT.REP@` flags are in [verb_tags.lexc](https://github.com/giellalt/lang-srs/blob/5d2ea440cce0c9b24485e96be4bcc54013224ac3/src/fst/affixes/verb_tags.lexc#L114).  Luckily for us, the superaspect flag doesn't interact much with other parts of the FST: repetitive verb forms don't have their own, distinctive TAMA chunks, and (in Tsuut'ina, at least) they don't come along with any unusual changes to other parts of the morphology (outside of the distinctive stem forms that we specify in lexical entries).  For our purposes, this flag basically only serves to distinguish 'plain' (i.e., non-repetitive) IPFV and PFV forms from their repetitive counterparts, allowing us to tag the latter as `+Rep`.

**Comment by aarppe** [comment]
Ok, I should have remembered that the repetitive superaspect was primarily a concern for the tagging, but now that's be explicitly considered (and recorded for future reference). I'll need to revise the automatic LEXC generation, though U and P flags should work similarly, with respect to a matching R flag.
