### ISSUE TITLE
Syntax error in S2 L rule?

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-srs#4]
The following rule does not make sense, and causes `hfst-xfst` to freak out:

https://github.com/giellalt/lang-srs/blob/90dd792bc9db1aab98a91216cb3d31dfcac9c499/src/fst/phonology.xfscript#L91

If the intended rule output is that there is free variation between the two, it  should be formulated in a different way, e.g. as follows:

```
define lInitialStemsSbjPl2 s2 l -> [ ł | s l ] ;
```

See also the nightly build report here: https://apertium.projectjj.com/apt/logs/giella-srs/sid-amd64.log

**Comment by coxchristopher** [comment]
Thanks for catching this, Sjur! I've checked in a fix to `lang-srs/src/fst/phonology.xfscript` now, and can confirm that the new code produces the intended variation for /l/-initial stems with 2PL subjects.
